### ISSUE TITLE
About coco related data

### ISSUE THREAD

**Issue by PenGuinoo97** [antoine77340/Mixture-of-Embedding-Experts#1]
Hello,

I am a student on Master 1, doing a research internship on subject related to video captioning. I find your work on MEE very inspiring and is trying to test your model. But I encountered a problem when running train.py on MSRVTT:

these two files are missing:
coco_visual_path='data/X_train2014_resnet152.npy' ,coco_text_path='data/w2v_coco_train2014_1.npy'

can you add these two files to the public ftp server?

Thanks in advance

**Comment by antoine77340** [comment]
Hi, Thank you for reporting me these missing files !
I re-uploaded the data.zip file so it includes these files.

Sorry for the troubles !
