### ISSUE TITLE
about test sentences

### ISSUE THREAD

**Issue by danieljf24** [antoine77340/Mixture-of-Embedding-Experts#13]
Hi Antoine,  many thanks for sharing the code and data. Recently I would like to compare with your wonderfull model on your split test set. But I only obtained the sentence feature of test sentences, I am wondering could you provide the original 1000 test sentences. Thanks very much.

**Comment by antoine77340** [comment]
Hi,
I guess you have downloaded the data.zip file from: https://www.rocq.inria.fr/cluster-willow/amiech/ECCV18/data.zip

This zip contains a text file called test_list.zip which are the videos ids of the MSRVTT video used at test time. For each of these videos, we took the very first sentence from the original MSRVTT json file that you can find on the MSRVTT website: http://ms-multimedia-challenge.com/2017/dataset.

**Comment by danieljf24** [comment]
Thanks Antoine
