### ISSUE TITLE
Web Demo link not working

### ISSUE THREAD

**Issue by estathop** [antoine77340/Mixture-of-Embedding-Experts#4]
What the title says, Web Demo link is not loading anything at all.

**Comment by antoine77340** [comment]
Yes I am currently having issues with my webserver and did not have time to investigate, are you interested in trying to web demo ? I can reboot the server tonight but I do not know how long it will take for it to crash again.

**Comment by antoine77340** [comment]
It is temporary back ! But it will still somehow be down after a while unfortunately.

**Comment by estathop** [comment]
I am trying to understand what you did exactly at your journal "Learning a Text-Video Embedding from incomplete and heterogeneous Data". I was hoping for a little bit more statistics.

**Comment by estathop** [comment]
closed
